config/routes.rb
Rails.application.routes.draw do

  get 'admin' => 'admin#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :users do
    post 'edit', on: :member
    post 'pdf', on: :collection
  end

  resources :products do
    get 'who_bought', on: :member
    resources :reviews
  end

  scope '(:locale)' do
    resources :orders do
      post 'ship', on: :member
    end
    resources :line_items do
      post 'decrement', on: :member
    end
    resources :carts
    root 'store#index', as: 'store_index', via: :all

  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  include ActiveModel::Serializers::Xml
  has_many :line_items
  has_many :reviews, dependent: :destroy
  has_many :orders, through: :line_items
  before_destroy :ensure_not_referenced_by_any_line_item
  validates :title, :description, :image_url, :locale, presence: true
  validates :price, numericality: {greater_than_or_equal_to: 0.01}
  validates :title, uniqueness: true
  validates :image_url, allow_blank: true, format: {
    with: %r{\.(gif|jpg|png)\Z}i,
    message: 'must be a URL for GIF, JPG or PNG image'
  }
  validates :title, length: {minimum: 10}
  validates :price, numericality: {less_than: 1000, message: 'is too high' }

  private
  #ensure there are no line items referencing this product
  def ensure_not_referenced_by_any_line_item
    unless line_items.empty?
      errors.add(:base, 'Line Items present')
      throw :abort
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  # GET /products
  # GET /products.json
  def index
    @products = Product.order(:title)
  end

  # GET /products/1
  # GET /products/1.json
  def show
    # respond_to do |format|
    #   format.html
    #   format.json { render json: @product.as_json }
    # end
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }

        @products = Product.order(:title)
        ActionCable.server.broadcast 'products',{
          product_id: "#{@product.id}",
          html: render_to_string("store/index", layout: false)}
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def who_bought
    @product = Product.find(params[:id])
    @latest_order = @product.orders.order(:updated_at).last
    if stale?(@latest_order)
      respond_to do |format|
        format.html
        format.atom
        format.json {render(json: @product.as_json(
          only: [:title, :updated_at],
          include: {
            orders: {
              except: [:created_at, :updated_at],
              include: {
                line_items: {
                  except: [:created_at, :updated_at, :cart_id, :order_id]
                }
              }
            }
          }
          ))}
        format.xml {render( xml: @product.to_xml(
          only: [:title, :updated_at],
          skip_types: true,
          include: {
            orders: {
              except: [:created_at, :updated_at],
              skip_types: true,
              include: {
                line_items: {
                  skip_types: true,
                  except: [:created_at, :updated_at, :cart_id, :order_id]
                }
              }
            }
          }
        ))}
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :description, :image_url, :price, :locale)
    end

    def decrement

    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for(product) do |f| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description, rows: 10, cols: 60 %>
  </div>

  <div class="field">
    <%= f.label :image_url %>
    <%= f.text_field :image_url %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>

  <div class="field">
    <%= f.label :locale %>
    <%= f.text_field :locale %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table>
  <% @products.each do |product| %>
    <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
      <td><%= image_tag(product.image_url, class: 'list_image') %></td>
      <td><%= product.locale.upcase %></td>
      <td class="list_description">
        <dl>
          <dt><%= product.title %></dt>
          <dd><%= truncate(strip_tags(product.description), length: 80) %></dd>
        </dl>
      </td>
      <td class="list_actions">
        <%= link_to 'Show', product %><br>
        <%= link_to 'Edit', edit_product_path(product) %><br>
        <%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %><br>
        <% n = product.reviews.count %>
        <%= link_to pluralize(n, 'Review') , product_reviews_path(product) %>
      </td>
    </tr>
  <% end %>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @product.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @product.image_url %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Locale:</strong>
  <%= @product.locale %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %> |
<%= link_to 'Reviews', product_reviews_path(@product) %>

app/views/products/who_bought.html.erb
<% @product.orders.each do |order| %>
<h2>Order id: <%= order.id %></h2>
<p>Customer name: <%= order.name %></p>
<p>Customer email: <%= order.email %></p>
<p>Shipped to <%= order.address %></p>
<table>
  <tr>
    <th>Product</th>
    <th>Quantity</th>
    <th>Total price</th>
  </tr>
  <% order.line_items.each do |item| %>
  <tr>
    <td><%= item.product.title %></td>
    <td><%= item.quantity %></td>
    <td><%= number_to_currency(item.total_price)%></td>
  </tr>
   <% end %>
   <tr>
     <th colspan="2">total</th>
     <th><%= number_to_currency(order.line_items.map(&:total_price).sum)%></th>
   </tr>
</table>
<p>Paid by <%= order.pay_type%></p>
<% end %>