config/routes.rb
Rails.application.routes.draw do

  get 'admin' => 'admin#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :users do
    post 'edit', on: :member
    post 'pdf', on: :collection
  end

  resources :products do
    get 'who_bought', on: :member
    resources :reviews
  end

  scope '(:locale)' do
    resources :orders do
      post 'ship', on: :member
    end
    resources :line_items do
      post 'decrement', on: :member
    end
    resources :carts
    root 'store#index', as: 'store_index', via: :all

  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Depot</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="<%= controller.controller_name %>">
    <div id="banner">
     <%= form_tag request.original_url, class: 'locale', method: :get do %>
      <%= select_tag 'set_locale',
          options_for_select(LANGUAGES, I18n.locale.to_s),
          onchange: 'this.form.submit()' %>
      <%= submit_tag 'submit' %>
      <%= javascript_tag "$('.locale input').hide()" %>
     <% end %>
     <%= image_tag 'logo.svg', alt: 'The Pragmatic Bookshelf'%>
     <span class="title"><%= page_title() %></span>
    </div>
    <div id="columns">
      <div id="side">
        <div style="color: white;">
          <%= controller.controller_name %>
          <%= controller.action_name %>
            :user_id <%= session[:user_id] %>
        </div>
        <p id="action_name" style="visibility: hidden;">
          <%= controller.action_name %>
        </p>
        <% if @cart %>
          <%= hidden_div_if(@cart.line_items.empty?, id: 'cart') do %>
            <%= render @cart %>
          <% end %>
        <% end %>

        <ul>
          <li><%= link_to t('.home'), store_index_url %></li>
          <li><a href="http://www.../faq"><%= t('.questions')%></a></li>
          <li><a href="http://www.../news"><%=t('.news')%></a></li>
          <li><a href="http://www.../contact"><%=t('.contact')%></a></li>
        </ul>

        <% if session[:user_id] %>
          <ul>
            <li><%= link_to 'Orders', orders_path %></li>
            <li><%= link_to 'Products', products_path %></li>
            <li><%= link_to 'Users', users_path %></li>
          </ul>
          <%= button_to 'Log out', logout_path, method: :delete %>
        <% end %>
        <% unless session[:user_id] %>
        <p><%= button_to 'Log in', login_path, method: :get %></p>
        <% end %>
      </div>
      <div id="main">
        <%= yield %>
        <p>parametrs: <%= request.original_url %></p>

      </div>
    </div>
  </body>
</html>